application: ligertailbackend
version: 6
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  secure: optional

- url: /frontend
  static_dir: frontend
  secure: optional
  
#- url: /frontend/css
#  static_dir: frontend/css
  
#- url: /frontend/images
#  static_dir: frontend/images  

#- url: /frontend/facebox
#  static_dir: frontnend/facebox

- url: /web/images
  static_dir: web/images
  
- url: /web/css
  static_dir: web/css
  
- url: /web/amline
  static_dir: web/amline
  
- url: /frontend/payment\.html
  secure: always
  static_dir: frontend

- url: /payment\.html
  secure: always
  script: main.py

- url: /webadmin
  script: main.py
  login: admin
      
- url: /api/.*
  script: main.py

- url: /.*
  script: main.py
  


