application: ligertailbackend
version: 5
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  secure: optional

- url: /frontend/payment\.html
  secure: always
  static_dir: frontend
  
- url: /frontend
  static_dir: frontend
  secure: optional
  
- url: /admin
  script: admin/admin.py
  login: admin
      
- url: .*
  script: main.py

