application: ligertailbackend
version: 5
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  secure: optional
  
- url: /frontend/css
  static_dir: frontend/css
  
- url: /frontend/images
  static_dir: frontend/images  

- url: /frontend/web/images
  static_dir: frontend/web/images
  
- url: /frontend/web/css
  static_dir: frontend/web/css
  
- url: /payment\.html
  script: main.py
  secure: always
    
- url: /admin
  script: admin/admin.py
  login: admin
      
- url: /.*
  script: main.py
  secure: optional

